---

port: 4000
host: 0.0.0.0
safe: false


### site serving configuration ###
exclude: [CNAME, README.md, .gitignore, scripts]
permalink: /:title ## disables post output
timezone: null
lsi: false
markdown: kramdown


### content configuration ###
title:       "GSoC 2017 @STEllAR-GROUP/hpx"
keywords:    "GSoC 2017, Denis Blank, HPX"
description: "This siteprovides the final report of my GSoC 2017 Project @STEllAR-GROUP"
source_link: "https://naios.github.io/gsoc2017"
favicon:     "img/favicon.ico"
touch_icon:  "img/apple-touch-icon.png"


### template colors, used site-wide via css ###
colors:
  myheader:  '#056A7F'
  black:     '#111111'
  white:     '#f8f8f8'
  blue:      '#49a7e9'
  green:     '#9bcf2f'
  purple:    '#c869bf'
  orange:    '#fab125'
  turquoise: '#0fbfcf'
  myblack:   '#23373B'
  myblacklight: '#24525B'
  mygrey:    '#F4F4F4'

kramdown:
  auto_ids:  false

